var a=[1,2,3,4,5,6,7,8,9,10];


var b=a.map(function(value)
{

    return value;
})



console.log(b);



let name=["Soham","Rahul","Mohan","Karan"];


let names=name.map(function(n){

    return n;
})


console.log(names);






const abc=[16,23,32,36,82];


const pqr=abc.map(function(element){

    return element;

})


console.log(pqr);




const array=[1,2,3,4,5,6,7,8];


const half=array.map(function(z){

    return z/2;
})

console.log(half);